#!/bin/bash

# used links
# https://docstore.mik.ua/orelly/networking_2ndEd/ssh/ch06_03.htm
# https://wafatech.sa/blog/linux/linux-security/enhancing-ssh-agent-security-on-linux-servers-best-practices/

( 
  eval "$(ssh-agent -s)"
  ssh-add -t 10m ~/.ssh/gh

  GIT_SSH_COMMAND='ssh -A' lazygit

  ssh-add -d ~/.ssh/gh
  pkill ssh-agent
)

